const mongoose = require('mongoose');

const categorySchema = mongoose.Schema({
    // The '_id' field is automatically generated by the ORM
    title: {
        type: String,
        required: true,
    },
    parent: {
        type: String,
        required: false,
    },
    path: {
        type: String,
        required: true,
    },
    status: {
        type: String,
        required: true,
        default: 'ACTIVE',
    },
}, {
    versionKey: false,
});

module.exports = mongoose.model('Category', categorySchema);
