const mongoose = require('mongoose');

const makerSchema = mongoose.Schema({
    // The '_id' field is automatically generated by the ORM
    name: {
        type: String,
        required: true,
    },
    document: {
        type: String,
        required: false,
    },
    status: {
        type: String,
        required: true,
        default: 'ACTIVE',
    },
}, {
    versionKey: false,
});

module.exports = mongoose.model('Maker', makerSchema);
