const mongoose = require('mongoose');

const productSchema = mongoose.Schema({
    // The '_id' field is automatically generated by the ORM
    sku: {
        type: String,
        required: true,
    },
    name: {
        type: String,
        required: true,
    },
    description: {
        type: String,
        required: true,
    },
    unit: {
        type: String,
        required: false,
    },
    expiration: {
        type: String,
        required: false,
    },
    model: {
        type: String,
        required: false,
    },
    quantity: {
        type: String,
        required: true,
    },
    price: {
        type: Number,
        required: true,
    },
    category: {
        type: String,
        required: true,
    },
    maker: {
        type: String,
        required: true,
    },
    images: [String],
    status: {
        type: String,
        required: true,
        default: 'ACTIVE',
    },
}, {
    versionKey: false,
});

module.exports = mongoose.model('Product', productSchema);
